import "./globals.css";
import { Inter } from "next/font/google";
import { Session } from "next-auth";
import { headers } from "next/headers";
import AuthContext from "./AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getSession(cookie: string): Promise<Session> {
  const response = await fetch(
    `${process.env.LOCAL_AUTH_URL}/api/auth/session`,
    {
      headers: {
        cookie,
      },
    }
  );

  const session = await response.json();

  return Object.keys(session).length > 0 ? session : null;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession(headers().get("cookie") ?? "");
  return (
    <html data-theme="dark" lang="en">
      <body className={`${inter.className} h-screen w-screen prose`}>
        <AuthContext session={session}>{children}</AuthContext>
      </body>
    </html>
  );
}
